<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- ========================= -->
    <!-- Mavenモデルバージョン -->
    <!-- ========================= -->
    <modelVersion>4.0.0</modelVersion>

    <!-- ========================= -->
    <!-- Spring Boot親設定 -->
    <!-- ========================= -->
    <parent>

        <groupId>
            org.springframework.boot
        </groupId>

        <artifactId>
            spring-boot-starter-parent
        </artifactId>

        <version>
            3.5.14
        </version>

        <relativePath/>

    </parent>

    <!-- ========================= -->
    <!-- プロジェクト情報 -->
    <!-- ========================= -->
    <groupId>
        com.takuya
    </groupId>

    <artifactId>
        travelmap
    </artifactId>

    <version>
        0.0.1-SNAPSHOT
    </version>

    <name>
        travelmap
    </name>

    <description>
        SNS + MAP Application
    </description>

    <!-- ========================= -->
    <!-- Javaバージョン -->
    <!-- ========================= -->
    <properties>

        <java.version>
            21
        </java.version>

    </properties>

    <!-- ========================= -->
    <!-- 使用ライブラリ -->
    <!-- ========================= -->
    <dependencies>

        <!-- ========================= -->
        <!-- Spring Web -->
        <!-- Controller / API -->
        <!-- ========================= -->
        <dependency>

            <groupId>
                org.springframework.boot
            </groupId>

            <artifactId>
                spring-boot-starter-web
            </artifactId>

        </dependency>

        <!-- ========================= -->
        <!-- Thymeleaf -->
        <!-- HTML画面表示 -->
        <!-- ========================= -->
        <dependency>

            <groupId>
                org.springframework.boot
            </groupId>

            <artifactId>
                spring-boot-starter-thymeleaf
            </artifactId>

        </dependency>

        <!-- ========================= -->
        <!-- JPA -->
        <!-- DB操作 -->
        <!-- ========================= -->
        <dependency>

            <groupId>
                org.springframework.boot
            </groupId>

            <artifactId>
                spring-boot-starter-data-jpa
            </artifactId>

        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

        <!-- ========================= -->
        <!-- Validation -->
        <!-- 入力チェック -->
        <!-- ========================= -->
        <dependency>

            <groupId>
                org.springframework.boot
            </groupId>

            <artifactId>
                spring-boot-starter-validation
            </artifactId>

        </dependency>

        <!-- ========================= -->
        <!-- BCrypt -->
        <!-- パスワード暗号化 -->
        <!-- ========================= -->
        <dependency>

            <groupId>
                org.springframework.security
            </groupId>

            <artifactId>
                spring-security-crypto
            </artifactId>

        </dependency>

        <!-- ========================= -->
        <!-- DevTools -->
        <!-- 自動リロード -->
        <!-- ========================= -->
        <dependency>

            <groupId>
                org.springframework.boot
            </groupId>

            <artifactId>
                spring-boot-devtools
            </artifactId>

            <scope>
                runtime
            </scope>

            <optional>
                true
            </optional>

        </dependency>

        <!-- ========================= -->
        <!-- Test -->
        <!-- テスト -->
        <!-- ========================= -->
        <dependency>

            <groupId>
                org.springframework.boot
            </groupId>

            <artifactId>
                spring-boot-starter-test
            </artifactId>

            <scope>
                test
            </scope>

        </dependency>

    </dependencies>

    <!-- ========================= -->
    <!-- Build設定 -->
    <!-- ========================= -->
    <build>

        <plugins>

            <!-- Spring Boot起動 -->
            <plugin>

                <groupId>
                    org.springframework.boot
                </groupId>

                <artifactId>
                    spring-boot-maven-plugin
                </artifactId>

            </plugin>

        </plugins>

    </build>

</project>
