# MySQL接続先
spring.datasource.url=jdbc:mysql://localhost:3306/travelmap

# MySQLユーザー名
spring.datasource.username=root

# MySQLパスワード
spring.datasource.password=Takuya9523

# DB自動更新
spring.jpa.hibernate.ddl-auto=update

# SQLログ表示
spring.jpa.show-sql=true